//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ERPForm.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ERPServiceSoap", Namespace="http://erpimlement.org/")]
    public partial class ERPService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EmployeeComboBoxOperationCompleted;
        
        private System.Threading.SendOrPostCallback MetaDataComboBoxOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmployeeMetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpRelativeMetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpAbsMetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpTopAbsMetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPKMetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndexesMetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllConstraintsMetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTable1MetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTable2MetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpColumns1MetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpColumns2MetaDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpRelativeDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpAbsDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpTopAbsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPKOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndexesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllConstraintsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTable1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTable2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpColumns1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmpColumns2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ERPService() {
            this.Url = global::ERPForm.Properties.Settings.Default.ERPForm_localhost_ERPService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EmployeeComboBoxCompletedEventHandler EmployeeComboBoxCompleted;
        
        /// <remarks/>
        public event MetaDataComboBoxCompletedEventHandler MetaDataComboBoxCompleted;
        
        /// <remarks/>
        public event GetEmployeeMetaDataCompletedEventHandler GetEmployeeMetaDataCompleted;
        
        /// <remarks/>
        public event GetEmpRelativeMetaDataCompletedEventHandler GetEmpRelativeMetaDataCompleted;
        
        /// <remarks/>
        public event GetEmpAbsMetaDataCompletedEventHandler GetEmpAbsMetaDataCompleted;
        
        /// <remarks/>
        public event GetEmpTopAbsMetaDataCompletedEventHandler GetEmpTopAbsMetaDataCompleted;
        
        /// <remarks/>
        public event GetAllPKMetaDataCompletedEventHandler GetAllPKMetaDataCompleted;
        
        /// <remarks/>
        public event GetIndexesMetaDataCompletedEventHandler GetIndexesMetaDataCompleted;
        
        /// <remarks/>
        public event GetAllConstraintsMetaDataCompletedEventHandler GetAllConstraintsMetaDataCompleted;
        
        /// <remarks/>
        public event GetTable1MetaDataCompletedEventHandler GetTable1MetaDataCompleted;
        
        /// <remarks/>
        public event GetTable2MetaDataCompletedEventHandler GetTable2MetaDataCompleted;
        
        /// <remarks/>
        public event GetEmpColumns1MetaDataCompletedEventHandler GetEmpColumns1MetaDataCompleted;
        
        /// <remarks/>
        public event GetEmpColumns2MetaDataCompletedEventHandler GetEmpColumns2MetaDataCompleted;
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetEmployeeCompletedEventHandler GetEmployeeCompleted;
        
        /// <remarks/>
        public event GetEmpRelativeDataCompletedEventHandler GetEmpRelativeDataCompleted;
        
        /// <remarks/>
        public event GetEmpAbsDataCompletedEventHandler GetEmpAbsDataCompleted;
        
        /// <remarks/>
        public event GetEmpTopAbsCompletedEventHandler GetEmpTopAbsCompleted;
        
        /// <remarks/>
        public event GetAllPKCompletedEventHandler GetAllPKCompleted;
        
        /// <remarks/>
        public event GetIndexesCompletedEventHandler GetIndexesCompleted;
        
        /// <remarks/>
        public event GetAllConstraintsCompletedEventHandler GetAllConstraintsCompleted;
        
        /// <remarks/>
        public event GetTable1CompletedEventHandler GetTable1Completed;
        
        /// <remarks/>
        public event GetTable2CompletedEventHandler GetTable2Completed;
        
        /// <remarks/>
        public event GetEmpColumns1CompletedEventHandler GetEmpColumns1Completed;
        
        /// <remarks/>
        public event GetEmpColumns2CompletedEventHandler GetEmpColumns2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/EmployeeComboBox", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] EmployeeComboBox() {
            object[] results = this.Invoke("EmployeeComboBox", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void EmployeeComboBoxAsync() {
            this.EmployeeComboBoxAsync(null);
        }
        
        /// <remarks/>
        public void EmployeeComboBoxAsync(object userState) {
            if ((this.EmployeeComboBoxOperationCompleted == null)) {
                this.EmployeeComboBoxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmployeeComboBoxOperationCompleted);
            }
            this.InvokeAsync("EmployeeComboBox", new object[0], this.EmployeeComboBoxOperationCompleted, userState);
        }
        
        private void OnEmployeeComboBoxOperationCompleted(object arg) {
            if ((this.EmployeeComboBoxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmployeeComboBoxCompleted(this, new EmployeeComboBoxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/MetaDataComboBox", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] MetaDataComboBox() {
            object[] results = this.Invoke("MetaDataComboBox", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void MetaDataComboBoxAsync() {
            this.MetaDataComboBoxAsync(null);
        }
        
        /// <remarks/>
        public void MetaDataComboBoxAsync(object userState) {
            if ((this.MetaDataComboBoxOperationCompleted == null)) {
                this.MetaDataComboBoxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMetaDataComboBoxOperationCompleted);
            }
            this.InvokeAsync("MetaDataComboBox", new object[0], this.MetaDataComboBoxOperationCompleted, userState);
        }
        
        private void OnMetaDataComboBoxOperationCompleted(object arg) {
            if ((this.MetaDataComboBoxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MetaDataComboBoxCompleted(this, new MetaDataComboBoxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetEmployeeMetaData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetEmployeeMetaData() {
            object[] results = this.Invoke("GetEmployeeMetaData", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmployeeMetaDataAsync() {
            this.GetEmployeeMetaDataAsync(null);
        }
        
        /// <remarks/>
        public void GetEmployeeMetaDataAsync(object userState) {
            if ((this.GetEmployeeMetaDataOperationCompleted == null)) {
                this.GetEmployeeMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmployeeMetaDataOperationCompleted);
            }
            this.InvokeAsync("GetEmployeeMetaData", new object[0], this.GetEmployeeMetaDataOperationCompleted, userState);
        }
        
        private void OnGetEmployeeMetaDataOperationCompleted(object arg) {
            if ((this.GetEmployeeMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmployeeMetaDataCompleted(this, new GetEmployeeMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetEmpRelativeMetaData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetEmpRelativeMetaData() {
            object[] results = this.Invoke("GetEmpRelativeMetaData", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpRelativeMetaDataAsync() {
            this.GetEmpRelativeMetaDataAsync(null);
        }
        
        /// <remarks/>
        public void GetEmpRelativeMetaDataAsync(object userState) {
            if ((this.GetEmpRelativeMetaDataOperationCompleted == null)) {
                this.GetEmpRelativeMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpRelativeMetaDataOperationCompleted);
            }
            this.InvokeAsync("GetEmpRelativeMetaData", new object[0], this.GetEmpRelativeMetaDataOperationCompleted, userState);
        }
        
        private void OnGetEmpRelativeMetaDataOperationCompleted(object arg) {
            if ((this.GetEmpRelativeMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpRelativeMetaDataCompleted(this, new GetEmpRelativeMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetEmpAbsMetaData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetEmpAbsMetaData() {
            object[] results = this.Invoke("GetEmpAbsMetaData", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpAbsMetaDataAsync() {
            this.GetEmpAbsMetaDataAsync(null);
        }
        
        /// <remarks/>
        public void GetEmpAbsMetaDataAsync(object userState) {
            if ((this.GetEmpAbsMetaDataOperationCompleted == null)) {
                this.GetEmpAbsMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpAbsMetaDataOperationCompleted);
            }
            this.InvokeAsync("GetEmpAbsMetaData", new object[0], this.GetEmpAbsMetaDataOperationCompleted, userState);
        }
        
        private void OnGetEmpAbsMetaDataOperationCompleted(object arg) {
            if ((this.GetEmpAbsMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpAbsMetaDataCompleted(this, new GetEmpAbsMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetEmpTopAbsMetaData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetEmpTopAbsMetaData() {
            object[] results = this.Invoke("GetEmpTopAbsMetaData", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpTopAbsMetaDataAsync() {
            this.GetEmpTopAbsMetaDataAsync(null);
        }
        
        /// <remarks/>
        public void GetEmpTopAbsMetaDataAsync(object userState) {
            if ((this.GetEmpTopAbsMetaDataOperationCompleted == null)) {
                this.GetEmpTopAbsMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpTopAbsMetaDataOperationCompleted);
            }
            this.InvokeAsync("GetEmpTopAbsMetaData", new object[0], this.GetEmpTopAbsMetaDataOperationCompleted, userState);
        }
        
        private void OnGetEmpTopAbsMetaDataOperationCompleted(object arg) {
            if ((this.GetEmpTopAbsMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpTopAbsMetaDataCompleted(this, new GetEmpTopAbsMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetAllPKMetaData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAllPKMetaData() {
            object[] results = this.Invoke("GetAllPKMetaData", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPKMetaDataAsync() {
            this.GetAllPKMetaDataAsync(null);
        }
        
        /// <remarks/>
        public void GetAllPKMetaDataAsync(object userState) {
            if ((this.GetAllPKMetaDataOperationCompleted == null)) {
                this.GetAllPKMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPKMetaDataOperationCompleted);
            }
            this.InvokeAsync("GetAllPKMetaData", new object[0], this.GetAllPKMetaDataOperationCompleted, userState);
        }
        
        private void OnGetAllPKMetaDataOperationCompleted(object arg) {
            if ((this.GetAllPKMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPKMetaDataCompleted(this, new GetAllPKMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetIndexesMetaData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetIndexesMetaData() {
            object[] results = this.Invoke("GetIndexesMetaData", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetIndexesMetaDataAsync() {
            this.GetIndexesMetaDataAsync(null);
        }
        
        /// <remarks/>
        public void GetIndexesMetaDataAsync(object userState) {
            if ((this.GetIndexesMetaDataOperationCompleted == null)) {
                this.GetIndexesMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndexesMetaDataOperationCompleted);
            }
            this.InvokeAsync("GetIndexesMetaData", new object[0], this.GetIndexesMetaDataOperationCompleted, userState);
        }
        
        private void OnGetIndexesMetaDataOperationCompleted(object arg) {
            if ((this.GetIndexesMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndexesMetaDataCompleted(this, new GetIndexesMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetAllConstraintsMetaData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAllConstraintsMetaData() {
            object[] results = this.Invoke("GetAllConstraintsMetaData", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllConstraintsMetaDataAsync() {
            this.GetAllConstraintsMetaDataAsync(null);
        }
        
        /// <remarks/>
        public void GetAllConstraintsMetaDataAsync(object userState) {
            if ((this.GetAllConstraintsMetaDataOperationCompleted == null)) {
                this.GetAllConstraintsMetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllConstraintsMetaDataOperationCompleted);
            }
            this.InvokeAsync("GetAllConstraintsMetaData", new object[0], this.GetAllConstraintsMetaDataOperationCompleted, userState);
        }
        
        private void OnGetAllConstraintsMetaDataOperationCompleted(object arg) {
            if ((this.GetAllConstraintsMetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllConstraintsMetaDataCompleted(this, new GetAllConstraintsMetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetTable1MetaData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetTable1MetaData() {
            object[] results = this.Invoke("GetTable1MetaData", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTable1MetaDataAsync() {
            this.GetTable1MetaDataAsync(null);
        }
        
        /// <remarks/>
        public void GetTable1MetaDataAsync(object userState) {
            if ((this.GetTable1MetaDataOperationCompleted == null)) {
                this.GetTable1MetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTable1MetaDataOperationCompleted);
            }
            this.InvokeAsync("GetTable1MetaData", new object[0], this.GetTable1MetaDataOperationCompleted, userState);
        }
        
        private void OnGetTable1MetaDataOperationCompleted(object arg) {
            if ((this.GetTable1MetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTable1MetaDataCompleted(this, new GetTable1MetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetTable2MetaData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetTable2MetaData() {
            object[] results = this.Invoke("GetTable2MetaData", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTable2MetaDataAsync() {
            this.GetTable2MetaDataAsync(null);
        }
        
        /// <remarks/>
        public void GetTable2MetaDataAsync(object userState) {
            if ((this.GetTable2MetaDataOperationCompleted == null)) {
                this.GetTable2MetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTable2MetaDataOperationCompleted);
            }
            this.InvokeAsync("GetTable2MetaData", new object[0], this.GetTable2MetaDataOperationCompleted, userState);
        }
        
        private void OnGetTable2MetaDataOperationCompleted(object arg) {
            if ((this.GetTable2MetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTable2MetaDataCompleted(this, new GetTable2MetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetEmpColumns1MetaData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetEmpColumns1MetaData() {
            object[] results = this.Invoke("GetEmpColumns1MetaData", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpColumns1MetaDataAsync() {
            this.GetEmpColumns1MetaDataAsync(null);
        }
        
        /// <remarks/>
        public void GetEmpColumns1MetaDataAsync(object userState) {
            if ((this.GetEmpColumns1MetaDataOperationCompleted == null)) {
                this.GetEmpColumns1MetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpColumns1MetaDataOperationCompleted);
            }
            this.InvokeAsync("GetEmpColumns1MetaData", new object[0], this.GetEmpColumns1MetaDataOperationCompleted, userState);
        }
        
        private void OnGetEmpColumns1MetaDataOperationCompleted(object arg) {
            if ((this.GetEmpColumns1MetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpColumns1MetaDataCompleted(this, new GetEmpColumns1MetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetEmpColumns2MetaData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetEmpColumns2MetaData() {
            object[] results = this.Invoke("GetEmpColumns2MetaData", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpColumns2MetaDataAsync() {
            this.GetEmpColumns2MetaDataAsync(null);
        }
        
        /// <remarks/>
        public void GetEmpColumns2MetaDataAsync(object userState) {
            if ((this.GetEmpColumns2MetaDataOperationCompleted == null)) {
                this.GetEmpColumns2MetaDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpColumns2MetaDataOperationCompleted);
            }
            this.InvokeAsync("GetEmpColumns2MetaData", new object[0], this.GetEmpColumns2MetaDataOperationCompleted, userState);
        }
        
        private void OnGetEmpColumns2MetaDataOperationCompleted(object arg) {
            if ((this.GetEmpColumns2MetaDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpColumns2MetaDataCompleted(this, new GetEmpColumns2MetaDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/HelloWorld", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetEmployee", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetEmployee() {
            object[] results = this.Invoke("GetEmployee", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmployeeAsync() {
            this.GetEmployeeAsync(null);
        }
        
        /// <remarks/>
        public void GetEmployeeAsync(object userState) {
            if ((this.GetEmployeeOperationCompleted == null)) {
                this.GetEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmployeeOperationCompleted);
            }
            this.InvokeAsync("GetEmployee", new object[0], this.GetEmployeeOperationCompleted, userState);
        }
        
        private void OnGetEmployeeOperationCompleted(object arg) {
            if ((this.GetEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmployeeCompleted(this, new GetEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetEmpRelativeData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetEmpRelativeData() {
            object[] results = this.Invoke("GetEmpRelativeData", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpRelativeDataAsync() {
            this.GetEmpRelativeDataAsync(null);
        }
        
        /// <remarks/>
        public void GetEmpRelativeDataAsync(object userState) {
            if ((this.GetEmpRelativeDataOperationCompleted == null)) {
                this.GetEmpRelativeDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpRelativeDataOperationCompleted);
            }
            this.InvokeAsync("GetEmpRelativeData", new object[0], this.GetEmpRelativeDataOperationCompleted, userState);
        }
        
        private void OnGetEmpRelativeDataOperationCompleted(object arg) {
            if ((this.GetEmpRelativeDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpRelativeDataCompleted(this, new GetEmpRelativeDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetEmpAbsData", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetEmpAbsData() {
            object[] results = this.Invoke("GetEmpAbsData", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpAbsDataAsync() {
            this.GetEmpAbsDataAsync(null);
        }
        
        /// <remarks/>
        public void GetEmpAbsDataAsync(object userState) {
            if ((this.GetEmpAbsDataOperationCompleted == null)) {
                this.GetEmpAbsDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpAbsDataOperationCompleted);
            }
            this.InvokeAsync("GetEmpAbsData", new object[0], this.GetEmpAbsDataOperationCompleted, userState);
        }
        
        private void OnGetEmpAbsDataOperationCompleted(object arg) {
            if ((this.GetEmpAbsDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpAbsDataCompleted(this, new GetEmpAbsDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetEmpTopAbs", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetEmpTopAbs() {
            object[] results = this.Invoke("GetEmpTopAbs", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpTopAbsAsync() {
            this.GetEmpTopAbsAsync(null);
        }
        
        /// <remarks/>
        public void GetEmpTopAbsAsync(object userState) {
            if ((this.GetEmpTopAbsOperationCompleted == null)) {
                this.GetEmpTopAbsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpTopAbsOperationCompleted);
            }
            this.InvokeAsync("GetEmpTopAbs", new object[0], this.GetEmpTopAbsOperationCompleted, userState);
        }
        
        private void OnGetEmpTopAbsOperationCompleted(object arg) {
            if ((this.GetEmpTopAbsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpTopAbsCompleted(this, new GetEmpTopAbsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetAllPK", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllPK() {
            object[] results = this.Invoke("GetAllPK", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPKAsync() {
            this.GetAllPKAsync(null);
        }
        
        /// <remarks/>
        public void GetAllPKAsync(object userState) {
            if ((this.GetAllPKOperationCompleted == null)) {
                this.GetAllPKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPKOperationCompleted);
            }
            this.InvokeAsync("GetAllPK", new object[0], this.GetAllPKOperationCompleted, userState);
        }
        
        private void OnGetAllPKOperationCompleted(object arg) {
            if ((this.GetAllPKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPKCompleted(this, new GetAllPKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetIndexes", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetIndexes() {
            object[] results = this.Invoke("GetIndexes", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetIndexesAsync() {
            this.GetIndexesAsync(null);
        }
        
        /// <remarks/>
        public void GetIndexesAsync(object userState) {
            if ((this.GetIndexesOperationCompleted == null)) {
                this.GetIndexesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndexesOperationCompleted);
            }
            this.InvokeAsync("GetIndexes", new object[0], this.GetIndexesOperationCompleted, userState);
        }
        
        private void OnGetIndexesOperationCompleted(object arg) {
            if ((this.GetIndexesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndexesCompleted(this, new GetIndexesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetAllConstraints", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllConstraints() {
            object[] results = this.Invoke("GetAllConstraints", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllConstraintsAsync() {
            this.GetAllConstraintsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllConstraintsAsync(object userState) {
            if ((this.GetAllConstraintsOperationCompleted == null)) {
                this.GetAllConstraintsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllConstraintsOperationCompleted);
            }
            this.InvokeAsync("GetAllConstraints", new object[0], this.GetAllConstraintsOperationCompleted, userState);
        }
        
        private void OnGetAllConstraintsOperationCompleted(object arg) {
            if ((this.GetAllConstraintsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllConstraintsCompleted(this, new GetAllConstraintsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetTable1", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetTable1() {
            object[] results = this.Invoke("GetTable1", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetTable1Async() {
            this.GetTable1Async(null);
        }
        
        /// <remarks/>
        public void GetTable1Async(object userState) {
            if ((this.GetTable1OperationCompleted == null)) {
                this.GetTable1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTable1OperationCompleted);
            }
            this.InvokeAsync("GetTable1", new object[0], this.GetTable1OperationCompleted, userState);
        }
        
        private void OnGetTable1OperationCompleted(object arg) {
            if ((this.GetTable1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTable1Completed(this, new GetTable1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetTable2", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetTable2() {
            object[] results = this.Invoke("GetTable2", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetTable2Async() {
            this.GetTable2Async(null);
        }
        
        /// <remarks/>
        public void GetTable2Async(object userState) {
            if ((this.GetTable2OperationCompleted == null)) {
                this.GetTable2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTable2OperationCompleted);
            }
            this.InvokeAsync("GetTable2", new object[0], this.GetTable2OperationCompleted, userState);
        }
        
        private void OnGetTable2OperationCompleted(object arg) {
            if ((this.GetTable2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTable2Completed(this, new GetTable2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetEmpColumns1", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetEmpColumns1() {
            object[] results = this.Invoke("GetEmpColumns1", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpColumns1Async() {
            this.GetEmpColumns1Async(null);
        }
        
        /// <remarks/>
        public void GetEmpColumns1Async(object userState) {
            if ((this.GetEmpColumns1OperationCompleted == null)) {
                this.GetEmpColumns1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpColumns1OperationCompleted);
            }
            this.InvokeAsync("GetEmpColumns1", new object[0], this.GetEmpColumns1OperationCompleted, userState);
        }
        
        private void OnGetEmpColumns1OperationCompleted(object arg) {
            if ((this.GetEmpColumns1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpColumns1Completed(this, new GetEmpColumns1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://erpimlement.org/GetEmpColumns2", RequestNamespace="http://erpimlement.org/", ResponseNamespace="http://erpimlement.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetEmpColumns2() {
            object[] results = this.Invoke("GetEmpColumns2", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmpColumns2Async() {
            this.GetEmpColumns2Async(null);
        }
        
        /// <remarks/>
        public void GetEmpColumns2Async(object userState) {
            if ((this.GetEmpColumns2OperationCompleted == null)) {
                this.GetEmpColumns2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmpColumns2OperationCompleted);
            }
            this.InvokeAsync("GetEmpColumns2", new object[0], this.GetEmpColumns2OperationCompleted, userState);
        }
        
        private void OnGetEmpColumns2OperationCompleted(object arg) {
            if ((this.GetEmpColumns2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmpColumns2Completed(this, new GetEmpColumns2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void EmployeeComboBoxCompletedEventHandler(object sender, EmployeeComboBoxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmployeeComboBoxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmployeeComboBoxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void MetaDataComboBoxCompletedEventHandler(object sender, MetaDataComboBoxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MetaDataComboBoxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MetaDataComboBoxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmployeeMetaDataCompletedEventHandler(object sender, GetEmployeeMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmployeeMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmployeeMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmpRelativeMetaDataCompletedEventHandler(object sender, GetEmpRelativeMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpRelativeMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpRelativeMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmpAbsMetaDataCompletedEventHandler(object sender, GetEmpAbsMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpAbsMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpAbsMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmpTopAbsMetaDataCompletedEventHandler(object sender, GetEmpTopAbsMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpTopAbsMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpTopAbsMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllPKMetaDataCompletedEventHandler(object sender, GetAllPKMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPKMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPKMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetIndexesMetaDataCompletedEventHandler(object sender, GetIndexesMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndexesMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndexesMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllConstraintsMetaDataCompletedEventHandler(object sender, GetAllConstraintsMetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllConstraintsMetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllConstraintsMetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetTable1MetaDataCompletedEventHandler(object sender, GetTable1MetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTable1MetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTable1MetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetTable2MetaDataCompletedEventHandler(object sender, GetTable2MetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTable2MetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTable2MetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmpColumns1MetaDataCompletedEventHandler(object sender, GetEmpColumns1MetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpColumns1MetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpColumns1MetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmpColumns2MetaDataCompletedEventHandler(object sender, GetEmpColumns2MetaDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpColumns2MetaDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpColumns2MetaDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmployeeCompletedEventHandler(object sender, GetEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmpRelativeDataCompletedEventHandler(object sender, GetEmpRelativeDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpRelativeDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpRelativeDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmpAbsDataCompletedEventHandler(object sender, GetEmpAbsDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpAbsDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpAbsDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmpTopAbsCompletedEventHandler(object sender, GetEmpTopAbsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpTopAbsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpTopAbsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllPKCompletedEventHandler(object sender, GetAllPKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetIndexesCompletedEventHandler(object sender, GetIndexesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndexesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndexesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllConstraintsCompletedEventHandler(object sender, GetAllConstraintsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllConstraintsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllConstraintsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetTable1CompletedEventHandler(object sender, GetTable1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTable1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTable1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetTable2CompletedEventHandler(object sender, GetTable2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTable2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTable2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmpColumns1CompletedEventHandler(object sender, GetEmpColumns1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpColumns1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpColumns1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmpColumns2CompletedEventHandler(object sender, GetEmpColumns2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmpColumns2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmpColumns2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591