//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPForm.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://erpimlement.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://erpimlement.org/", ConfigurationName="ServiceReference1.ERPServiceSoap")]
    public interface ERPServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://erpimlement.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://erpimlement.org/HelloWorld", ReplyAction="*")]
        ERPForm.ServiceReference1.HelloWorldResponse HelloWorld(ERPForm.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://erpimlement.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPForm.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ERPForm.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name s from namespace http://erpimlement.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://erpimlement.org/Fill", ReplyAction="*")]
        ERPForm.ServiceReference1.FillResponse Fill(ERPForm.ServiceReference1.FillRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://erpimlement.org/Fill", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPForm.ServiceReference1.FillResponse> FillAsync(ERPForm.ServiceReference1.FillRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmpTblResult from namespace http://erpimlement.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://erpimlement.org/GetEmpTbl", ReplyAction="*")]
        ERPForm.ServiceReference1.GetEmpTblResponse GetEmpTbl(ERPForm.ServiceReference1.GetEmpTblRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://erpimlement.org/GetEmpTbl", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPForm.ServiceReference1.GetEmpTblResponse> GetEmpTblAsync(ERPForm.ServiceReference1.GetEmpTblRequest request);
        
        // CODEGEN: Generating message contract since element name ShowAbsDataResult from namespace http://erpimlement.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://erpimlement.org/ShowAbsData", ReplyAction="*")]
        ERPForm.ServiceReference1.ShowAbsDataResponse ShowAbsData(ERPForm.ServiceReference1.ShowAbsDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://erpimlement.org/ShowAbsData", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPForm.ServiceReference1.ShowAbsDataResponse> ShowAbsDataAsync(ERPForm.ServiceReference1.ShowAbsDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://erpimlement.org/", Order=0)]
        public ERPForm.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ERPForm.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://erpimlement.org/", Order=0)]
        public ERPForm.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ERPForm.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://erpimlement.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fill", Namespace="http://erpimlement.org/", Order=0)]
        public ERPForm.ServiceReference1.FillRequestBody Body;
        
        public FillRequest() {
        }
        
        public FillRequest(ERPForm.ServiceReference1.FillRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://erpimlement.org/")]
    public partial class FillRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public FillRequestBody() {
        }
        
        public FillRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FillResponse", Namespace="http://erpimlement.org/", Order=0)]
        public ERPForm.ServiceReference1.FillResponseBody Body;
        
        public FillResponse() {
        }
        
        public FillResponse(ERPForm.ServiceReference1.FillResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://erpimlement.org/")]
    public partial class FillResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERPForm.ServiceReference1.ArrayOfString[] FillResult;
        
        public FillResponseBody() {
        }
        
        public FillResponseBody(ERPForm.ServiceReference1.ArrayOfString[] FillResult) {
            this.FillResult = FillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmpTblRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmpTbl", Namespace="http://erpimlement.org/", Order=0)]
        public ERPForm.ServiceReference1.GetEmpTblRequestBody Body;
        
        public GetEmpTblRequest() {
        }
        
        public GetEmpTblRequest(ERPForm.ServiceReference1.GetEmpTblRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmpTblRequestBody {
        
        public GetEmpTblRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmpTblResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmpTblResponse", Namespace="http://erpimlement.org/", Order=0)]
        public ERPForm.ServiceReference1.GetEmpTblResponseBody Body;
        
        public GetEmpTblResponse() {
        }
        
        public GetEmpTblResponse(ERPForm.ServiceReference1.GetEmpTblResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://erpimlement.org/")]
    public partial class GetEmpTblResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERPForm.ServiceReference1.ArrayOfString GetEmpTblResult;
        
        public GetEmpTblResponseBody() {
        }
        
        public GetEmpTblResponseBody(ERPForm.ServiceReference1.ArrayOfString GetEmpTblResult) {
            this.GetEmpTblResult = GetEmpTblResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowAbsDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowAbsData", Namespace="http://erpimlement.org/", Order=0)]
        public ERPForm.ServiceReference1.ShowAbsDataRequestBody Body;
        
        public ShowAbsDataRequest() {
        }
        
        public ShowAbsDataRequest(ERPForm.ServiceReference1.ShowAbsDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShowAbsDataRequestBody {
        
        public ShowAbsDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowAbsDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowAbsDataResponse", Namespace="http://erpimlement.org/", Order=0)]
        public ERPForm.ServiceReference1.ShowAbsDataResponseBody Body;
        
        public ShowAbsDataResponse() {
        }
        
        public ShowAbsDataResponse(ERPForm.ServiceReference1.ShowAbsDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://erpimlement.org/")]
    public partial class ShowAbsDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERPForm.ServiceReference1.ArrayOfString[] ShowAbsDataResult;
        
        public ShowAbsDataResponseBody() {
        }
        
        public ShowAbsDataResponseBody(ERPForm.ServiceReference1.ArrayOfString[] ShowAbsDataResult) {
            this.ShowAbsDataResult = ShowAbsDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ERPServiceSoapChannel : ERPForm.ServiceReference1.ERPServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ERPServiceSoapClient : System.ServiceModel.ClientBase<ERPForm.ServiceReference1.ERPServiceSoap>, ERPForm.ServiceReference1.ERPServiceSoap {
        
        public ERPServiceSoapClient() {
        }
        
        public ERPServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ERPServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERPServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERPServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPForm.ServiceReference1.HelloWorldResponse ERPForm.ServiceReference1.ERPServiceSoap.HelloWorld(ERPForm.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ERPForm.ServiceReference1.HelloWorldRequest inValue = new ERPForm.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ERPForm.ServiceReference1.HelloWorldRequestBody();
            ERPForm.ServiceReference1.HelloWorldResponse retVal = ((ERPForm.ServiceReference1.ERPServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPForm.ServiceReference1.HelloWorldResponse> ERPForm.ServiceReference1.ERPServiceSoap.HelloWorldAsync(ERPForm.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPForm.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ERPForm.ServiceReference1.HelloWorldRequest inValue = new ERPForm.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ERPForm.ServiceReference1.HelloWorldRequestBody();
            return ((ERPForm.ServiceReference1.ERPServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPForm.ServiceReference1.FillResponse ERPForm.ServiceReference1.ERPServiceSoap.Fill(ERPForm.ServiceReference1.FillRequest request) {
            return base.Channel.Fill(request);
        }
        
        public ERPForm.ServiceReference1.ArrayOfString[] Fill(string s) {
            ERPForm.ServiceReference1.FillRequest inValue = new ERPForm.ServiceReference1.FillRequest();
            inValue.Body = new ERPForm.ServiceReference1.FillRequestBody();
            inValue.Body.s = s;
            ERPForm.ServiceReference1.FillResponse retVal = ((ERPForm.ServiceReference1.ERPServiceSoap)(this)).Fill(inValue);
            return retVal.Body.FillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPForm.ServiceReference1.FillResponse> ERPForm.ServiceReference1.ERPServiceSoap.FillAsync(ERPForm.ServiceReference1.FillRequest request) {
            return base.Channel.FillAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPForm.ServiceReference1.FillResponse> FillAsync(string s) {
            ERPForm.ServiceReference1.FillRequest inValue = new ERPForm.ServiceReference1.FillRequest();
            inValue.Body = new ERPForm.ServiceReference1.FillRequestBody();
            inValue.Body.s = s;
            return ((ERPForm.ServiceReference1.ERPServiceSoap)(this)).FillAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPForm.ServiceReference1.GetEmpTblResponse ERPForm.ServiceReference1.ERPServiceSoap.GetEmpTbl(ERPForm.ServiceReference1.GetEmpTblRequest request) {
            return base.Channel.GetEmpTbl(request);
        }
        
        public ERPForm.ServiceReference1.ArrayOfString GetEmpTbl() {
            ERPForm.ServiceReference1.GetEmpTblRequest inValue = new ERPForm.ServiceReference1.GetEmpTblRequest();
            inValue.Body = new ERPForm.ServiceReference1.GetEmpTblRequestBody();
            ERPForm.ServiceReference1.GetEmpTblResponse retVal = ((ERPForm.ServiceReference1.ERPServiceSoap)(this)).GetEmpTbl(inValue);
            return retVal.Body.GetEmpTblResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPForm.ServiceReference1.GetEmpTblResponse> ERPForm.ServiceReference1.ERPServiceSoap.GetEmpTblAsync(ERPForm.ServiceReference1.GetEmpTblRequest request) {
            return base.Channel.GetEmpTblAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPForm.ServiceReference1.GetEmpTblResponse> GetEmpTblAsync() {
            ERPForm.ServiceReference1.GetEmpTblRequest inValue = new ERPForm.ServiceReference1.GetEmpTblRequest();
            inValue.Body = new ERPForm.ServiceReference1.GetEmpTblRequestBody();
            return ((ERPForm.ServiceReference1.ERPServiceSoap)(this)).GetEmpTblAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPForm.ServiceReference1.ShowAbsDataResponse ERPForm.ServiceReference1.ERPServiceSoap.ShowAbsData(ERPForm.ServiceReference1.ShowAbsDataRequest request) {
            return base.Channel.ShowAbsData(request);
        }
        
        public ERPForm.ServiceReference1.ArrayOfString[] ShowAbsData() {
            ERPForm.ServiceReference1.ShowAbsDataRequest inValue = new ERPForm.ServiceReference1.ShowAbsDataRequest();
            inValue.Body = new ERPForm.ServiceReference1.ShowAbsDataRequestBody();
            ERPForm.ServiceReference1.ShowAbsDataResponse retVal = ((ERPForm.ServiceReference1.ERPServiceSoap)(this)).ShowAbsData(inValue);
            return retVal.Body.ShowAbsDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPForm.ServiceReference1.ShowAbsDataResponse> ERPForm.ServiceReference1.ERPServiceSoap.ShowAbsDataAsync(ERPForm.ServiceReference1.ShowAbsDataRequest request) {
            return base.Channel.ShowAbsDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPForm.ServiceReference1.ShowAbsDataResponse> ShowAbsDataAsync() {
            ERPForm.ServiceReference1.ShowAbsDataRequest inValue = new ERPForm.ServiceReference1.ShowAbsDataRequest();
            inValue.Body = new ERPForm.ServiceReference1.ShowAbsDataRequestBody();
            return ((ERPForm.ServiceReference1.ERPServiceSoap)(this)).ShowAbsDataAsync(inValue);
        }
    }
}
